#!/bin/sh

: ${LIBOPENRELEASE:=/usr/lib/libopenrelease.so}
: ${RELEASE:=/mnt/lg/lgapp/RELEASE}

export LD_LIBRARY_PATH=${LIBOPENRELEASE%/*}:${LD_LIBRARY_PATH}
export LD_PRELOAD=libopenrelease.so

exec ${RELEASE} $@
