#!/bin/sh

# Force unset of LOAD_SYM because generated .sym file
#  isn't correctly processed by the RELEASE.
unset LOAD_SYM

cd ${0%/*}/bin

export LD_LIBRARY_PATH=../lib:${LD_LIBRARY_PATH}
exec ./RELEASE $@
