TOOLCHAIN ?= mipsel-linux-uclibc-
LG_TOOLS ?=
KERNEL_SOURCES ?= ../opensrc/GPL/linux-2.6.26

RELEASE_LIB ?= ../LGLib_355
PAK_VERSION ?= 3.55.01
EPK_VERSION ?= 3.55.0

PLATFORM = SATURN6
PLATFORM_NAME ?= DVB-SATURN6
PLATFORM_ID ?= HE_DTV_GP_M_AAAAABAA
