RELEASE_LIB ?= ../RELEASELib
RELEASE_CFG ?= ../RELEASE.cfg
RELEASE_VERSION ?= 3.55
PLATFORM_NAME ?= DVB-SATURN6
PLATFORM_ID ?= HE_DTV_GP_M_AAAAABAA
OPENRELEASE_CONFIG ?= cfg/openrelease.cfg
OPENRELEASE_KEYMAP ?= cfg/openrelease_keymap.cfg
KERNEL_SOURCES ?= ../../opensrc/GPL/linux-2.6.26
