#!/bin/sh

# check format
echo $1 | sed -e '/^[0-9]\{1,2\}\(\.[0-9]\{1,2\}\(\.[0-9]\{1,2\}\(\.[0-9]\{1,2\}\)\?\)\?\)\?$/!q 1' > /dev/null
if [ $? -eq 1 ]
then
	exit 1
fi

# convert
echo $1 | sed -e ':loop s/\(^\|\.\)\([0-9]\)\($\|\.\)/\10\2\3/; t loop; s/\.//g; s/^/0x/'
